.PHONY: check

check:
	@test -z "$$(gofmt -l $$(find cmd internal -name '*.go' -type f))"
	@for script in scripts/adaptations/forgejo/* scripts/run-body/*; do sh -n "$$script" || exit 1; done
	go vet ./...
	go test ./...
	node --test workflows/*_test.mjs
	go build ./...
