.PHONY: check

check:
	@test -z "$$(gofmt -l $$(find cmd internal -name '*.go' -type f))"
	@for script in scripts/adaptations/forgejo/* scripts/run-body/*; do sh -n "$$script"; done
	go vet ./...
	go test ./...
	go build ./...
