#!/usr/bin/env sh
set -eu
# shellcheck source-path=SCRIPTDIR
. "$(dirname "$0")/common.sh"

owner="$1"
repo="$2"
pr="$3"

comments='[]'
previous=''
page=1
while :; do
  current="$(api GET "/api/v1/repos/${owner}/${repo}/issues/${pr}/comments?limit=50&page=${page}")"
  [ "$current" != "$previous" ] || break
  [ "$(printf '%s' "$current" | jq 'length')" -gt 0 ] || break
  comments="$(jq -cn --argjson all "$comments" --argjson page "$current" '$all + $page')"
  previous="$current"
  page=$((page + 1))
done

printf '%s' "$comments" | jq '[.[] | {id, body:(.body // ""), user:(.user.login // .user.username // "")}]'
