#!/usr/bin/env sh
set -eu
. "$(dirname "$0")/common.sh"

owner="$1"
repo="$2"
pr="$3"

api GET "/api/v1/repos/${owner}/${repo}/issues/${pr}/timeline" |
  jq -r '
    [.[] | select((.label.name // "") != "" and ((.type // "") | test("label"; "i")))][-1] as $event
    | if $event == null then
        "ACTION=\nLABEL=\nACTOR="
      else
        "ACTION=" + (if (($event.type // "") | test("unlabel|remove|delete|clear"; "i")) then "removed" else "added" end),
        "LABEL=" + ($event.label.name // ""),
        "ACTOR=" + ($event.user.login // $event.user.username // "")
      end
  '
