#!/usr/bin/env sh
set -eu
. "$(dirname "$0")/common.sh"

owner="$1"
repo="$2"

api GET "/api/v1/repos/${owner}/${repo}/pulls?state=open" |
  jq -r '.[] | [
    "OCCASION=reconcile",
    "FORGE=",
    ("OWNER=" + "'"$owner"'"),
    ("REPO=" + "'"$repo"'"),
    ("PR=" + ((.number // .index) | tostring)),
    ("HEAD_SHA=" + .head.sha),
    ("BASE_REF=" + .base.ref),
    ("AUTHOR=" + (.user.login // .user.username // "")),
    "ACTOR=",
    ("DRAFT=" + ((.draft // false) | tostring)),
    ("LABELS=" + ([.labels[]?.name] | join(",")))
  ] | .[], ""'
