#!/usr/bin/env sh
set -eu
# shellcheck source-path=SCRIPTDIR
. "$(dirname "$0")/common.sh"

owner="$1"
repo="$2"
comment_id="$3"
body_file="$4"

api PATCH "/api/v1/repos/${owner}/${repo}/issues/comments/${comment_id}" \
  -H "Content-Type: application/json" \
  --data "$(jq -nc --arg body "$(cat "$body_file")" '{body:$body}')"
